services:
  web:
    build: .
    container_name: school-frontend-nextjs
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:3000
    restart: unless-stopped
